Fail trap check on no process found

diff --git a/.github/workflows/cd_staging.yaml b/.github/workflows/cd_staging.yaml
--- a/.github/workflows/cd_staging.yaml
+++ b/.github/workflows/cd_staging.yaml
@@ -119,7 +119,8 @@ jobs:
           envs: CLOUD_API_KEY, CLOUD_API_SECRET, CLOUD_NAME, ENABLE_MORGAN, JWT_EXPIRES_IN, PORT, JWT_SECRET, MONGO_URL, NEXT_PUBLIC_API_URL, NODE_ENV, PRODUCTION_CLIENT_URL1, PRODUCTION_CLIENT_URL2
           script: |
             set -Eeuo pipefail
-
+            BACKEND_PORT=5006
+            FRONTEND_PORT=3006
             APP_NAME="portfolio"
             BASE_DIR="$HOME/apps/${APP_NAME}"
             RELEASES_DIR="${BASE_DIR}/releases"
@@ -213,25 +214,29 @@ jobs:
 
             trap rollback ERR
 
-            echo "backend entry ${RELEASE_DIR}/backend/server.js"
+            ################################################################
+            # START BACKEND
+            ################################################################
+
             BACKEND_ENTRY="${RELEASE_DIR}/backend/server.js"
 
-            # if [ ! -f "${BACKEND_ENTRY}" ]; then
-            #   echo "ERROR: Backend entry not found at ${BACKEND_ENTRY}"
-            #   exit 1
-            # fi
-            echo "check passed"
- 
-            pm2 list | grep -q "${APP_NAME}-backend" && pm2 describe ${APP_NAME}-backend >/dev/null 2>&1 && pm2 delete ${APP_NAME}-backend
-            echo "Describe app checked"
+            if [ ! -f "${BACKEND_ENTRY}" ]; then
+              echo "ERROR: Backend entry not found at ${BACKEND_ENTRY}"
+              exit 1
+            fi
+            echo "Backend Entry found continuing..."
+             
+            if pm2 describe "${APP_NAME}-backend" >/dev/null 2>&1; then
+                pm2 delete "${APP_NAME}-backend"
+            fi
 
-            pm2 start "${BACKEND_ENTRY}" \
+            PORT=${BACKEND_PORT} pm2 start "${BACKEND_ENTRY}" \
               --name ${APP_NAME}-backend \
               --cwd  "${RELEASE_DIR}/backend" \
               --time
             echo "Backend started"
 
-            
+
             ################################################################
             # START FRONTEND
             ################################################################
@@ -244,9 +249,11 @@ jobs:
               exit 1
             fi
 
-            pm2 describe ${APP_NAME}-frontend >/dev/null 2>&1 && pm2 delete ${APP_NAME}-frontend
+            if pm2 describe "${APP_NAME}-backend" >/dev/null 2>&1; then
+                pm2 delete "${APP_NAME}-backend"
+            fi
 
-            pm2 start "${FRONTEND_ENTRY}" \
+            PORT=${FRONTEND_PORT}pm2 start "${FRONTEND_ENTRY}" \
               --name ${APP_NAME}-frontend \
               --cwd  "${RELEASE_DIR}/frontend/standalone" \
               --time
@@ -256,7 +263,7 @@ jobs:
             for i in $(seq 1 15); do
                 if curl -fsS --max-time 5 http://localhost:/api/v1/health; then
                     echo "Backend healthy ✓"
-                    exit 0
+                    break
                 fi
 
                 sleep 2
