Backend and frontend entries check

diff --git a/.github/workflows/cd_staging.yaml b/.github/workflows/cd_staging.yaml
--- a/.github/workflows/cd_staging.yaml
+++ b/.github/workflows/cd_staging.yaml
@@ -119,7 +119,8 @@ jobs:
           envs: CLOUD_API_KEY, CLOUD_API_SECRET, CLOUD_NAME, ENABLE_MORGAN, JWT_EXPIRES_IN, PORT, JWT_SECRET, MONGO_URL, NEXT_PUBLIC_API_URL, NODE_ENV, PRODUCTION_CLIENT_URL1, PRODUCTION_CLIENT_URL2
           script: |
             set -Eeuo pipefail
-
+            BACKEND_PORT=5006
+            FRONTEND_PORT=3006
             APP_NAME="portfolio"
             BASE_DIR="$HOME/apps/${APP_NAME}"
             RELEASES_DIR="${BASE_DIR}/releases"
@@ -214,22 +215,25 @@ jobs:
             trap rollback ERR
 
             echo "backend entry ${RELEASE_DIR}/backend/server.js"
-            BACKEND_ENTRY="${RELEASE_DIR}/backend/server.js"
+            BACKEND_ENTRY="${RELEASE_DIR}/backend/server.js"  
 
-            # if [ ! -f "${BACKEND_ENTRY}" ]; then
-            #   echo "ERROR: Backend entry not found at ${BACKEND_ENTRY}"
-            #   exit 1
-            # fi
-            echo "check passed"
- 
-            pm2 list | grep -q "${APP_NAME}-backend" && pm2 describe ${APP_NAME}-backend >/dev/null 2>&1 && pm2 delete ${APP_NAME}-backend
-            echo "Describe app checked"
+            if [ ! -f "${BACKEND_ENTRY}" ]; then
+              echo "ERROR: Backend entry not found at ${BACKEND_ENTRY}"
+              exit 1
+            fi
+            echo "Backend entry found"
+            
+            if pm2 describe "${APP_NAME}-backend" >/dev/null 2>&1; then
+              echo "Restarting ${APP_NAME}-backend"
+              pm2 restart "${APP_NAME}-backend"
+            else
+              echo "Starting ${APP_NAME}-backend for the first time"
+              PORT=${BACKEND_PORT} pm2 start server.js \
+                --name "${APP_NAME}-backend" \
+                --cwd  "${RELEASE_DIR}/backend" \
+            fi
 
-            pm2 start "${BACKEND_ENTRY}" \
-              --name ${APP_NAME}-backend \
-              --cwd  "${RELEASE_DIR}/backend" \
-              --time
-            echo "Backend started"
+
             ################################################################
             # START FRONTEND
             ################################################################
@@ -242,17 +246,20 @@ jobs:
               exit 1
             fi
 
-            pm2 list | grep -q "${APP_NAME}-frontend" && pm2 describe ${APP_NAME}-frontend >/dev/null 2>&1 && pm2 delete ${APP_NAME}-frontend
-
-            pm2 start "${FRONTEND_ENTRY}" \
-              --name ${APP_NAME}-frontend \
-              --cwd  "${RELEASE_DIR}/frontend/standalone" \
-              --time
+            if pm2 describe "${APP_NAME}-frontend" >/dev/null 2>&1; then
+              echo "Restarting ${APP_NAME}-frontend"
+              pm2 restart "${APP_NAME}-frontend"
+            else
+              echo "Starting ${APP_NAME}-frontend for the first time"
+              PORT=${FRONTEND_PORT} pm2 start server.js \
+                --name "${APP_NAME}-frontend" \
+                --cwd  "${RELEASE_DIR}/frontend/standalone" 
+            fi
 
             echo "Waiting for services to boot..."
 
             for i in $(seq 1 15); do
-                if curl -fsS --max-time 5 http://localhost:/api/v1/health; then
+                if curl -fsS --max-time 5 http://localhost:${BACKEND_PORT}/api/v1/health; then
                     echo "Backend healthy ✓"
                     exit 0
                 fi
@@ -262,7 +269,7 @@ jobs:
             echo "ERROR: Backend health check failed"
             exit 1
 
-            if ! curl -fsS --max-time 10 http://localhost:3000; then
+            if ! curl -fsS --max-time 10 http://localhost:${FRONTEND_PORT}; then
               echo "ERROR: Frontend health check failed"
               exit 1
             fi
